// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpvGNtQAyUDmOpuuA0GnvEhzPPwmaBM80',
    appId: '1:466855690596:web:68de228cd92c385e353a71',
    messagingSenderId: '466855690596',
    projectId: 'excelerate-lms-de36a',
    authDomain: 'excelerate-lms-de36a.firebaseapp.com',
    storageBucket: 'excelerate-lms-de36a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGQZkJXkiXe3KzUAGdebkGgsJCfaBm8WQ',
    appId: '1:466855690596:android:f782979ccbcb4ed2353a71',
    messagingSenderId: '466855690596',
    projectId: 'excelerate-lms-de36a',
    storageBucket: 'excelerate-lms-de36a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4hvI9ckkQWcMMAP-dr6Bj9YJnepI_-9I',
    appId: '1:466855690596:ios:68bce544d0393066353a71',
    messagingSenderId: '466855690596',
    projectId: 'excelerate-lms-de36a',
    storageBucket: 'excelerate-lms-de36a.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4hvI9ckkQWcMMAP-dr6Bj9YJnepI_-9I',
    appId: '1:466855690596:ios:68bce544d0393066353a71',
    messagingSenderId: '466855690596',
    projectId: 'excelerate-lms-de36a',
    storageBucket: 'excelerate-lms-de36a.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpvGNtQAyUDmOpuuA0GnvEhzPPwmaBM80',
    appId: '1:466855690596:web:c1a651f0635ca129353a71',
    messagingSenderId: '466855690596',
    projectId: 'excelerate-lms-de36a',
    authDomain: 'excelerate-lms-de36a.firebaseapp.com',
    storageBucket: 'excelerate-lms-de36a.firebasestorage.app',
  );
}
